TELEGRAM_BOT_TOKEN={{ tg_token }}
TELEGRAM_TOKEN={{ tg_token }}
APP_KEY={{ app_key }}
APP_DEBUG=false
APP_TIMEZONE=UTC
APP_URL=arcana.juliamorg.com
LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
LOG_STACK=stderr,sentry,console,stdout
SENTRY_LARAVEL_DSN={{ sentry_dsn }}
SENTRY_TRACES_SAMPLE_RATE=1.0
SENTRY_RELEASE=$HOSTNAME
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=arcana
DB_USERNAME=arcana
DB_PASSWORD={{ pg_password }}
OPENAI_API_KEY={{ openai_key }}
